services:
  - type: web
    name: cinetop-backend
    env: node
    buildCommand: "npm install"
    startCommand: "npm start"
    plan: free
    envVars:
      - key: MONGO_URI
        value: mongodb+srv://cinetop:<SUA_SENHA>@aylton.1ihru9r.mongodb.net/?retryWrites=true&w=majority&appName=aylton
      - key: JWT_SECRET
        value: 684188b95169f27623efad11